# Pre-commit hooks to run tests and ensure code is cleaned.
# See https://pre-commit.com for more information
---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--no-error-on-unmatched-pattern", "--print-width", "100"]
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: uncrustify
        args: ["-c", ".uncrustify.cfg", "--replace", "--no-backup"]
