# Pre-commit hooks to run tests and ensure code is cleaned.
# See https://pre-commit.com for more information
---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: ["--print-width", "100"]
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: uncrustify
        args: ["-c", ".uncrustify.cfg", "--replace", "--no-backup"]
